/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface EasyBetInterface extends utils.Interface {
  functions: {
    "_activityCounter()": FunctionFragment;
    "betTicket()": FunctionFragment;
    "betToken()": FunctionFragment;
    "buyTicket(uint256)": FunctionFragment;
    "claimWinnings(uint256)": FunctionFragment;
    "createActivity(string,string[],uint256,uint256)": FunctionFragment;
    "getActivity(uint256)": FunctionFragment;
    "getChoiceBetAmount(uint256,uint256)": FunctionFragment;
    "listTicket(uint256,uint256)": FunctionFragment;
    "notary()": FunctionFragment;
    "placeBet(uint256,uint256,uint256)": FunctionFragment;
    "resolveActivity(uint256,uint256)": FunctionFragment;
    "sellOrders(uint256)": FunctionFragment;
    "unlistTicket(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_activityCounter"
      | "betTicket"
      | "betToken"
      | "buyTicket"
      | "claimWinnings"
      | "createActivity"
      | "getActivity"
      | "getChoiceBetAmount"
      | "listTicket"
      | "notary"
      | "placeBet"
      | "resolveActivity"
      | "sellOrders"
      | "unlistTicket"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_activityCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "betTicket", values?: undefined): string;
  encodeFunctionData(functionFragment: "betToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyTicket",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createActivity",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getActivity",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getChoiceBetAmount",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "listTicket",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "notary", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveActivity",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "sellOrders",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "unlistTicket",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "_activityCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "betTicket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "betToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChoiceBetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listTicket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "notary", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellOrders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlistTicket",
    data: BytesLike
  ): Result;

  events: {
    "ActivityCreated(uint256,string,string[],uint256,uint256)": EventFragment;
    "ActivityResolved(uint256,uint256)": EventFragment;
    "BetPlaced(uint256,address,uint256,uint256,uint256)": EventFragment;
    "TicketListed(uint256,address,uint256)": EventFragment;
    "TicketSold(uint256,address,address,uint256)": EventFragment;
    "TicketUnlisted(uint256)": EventFragment;
    "WinningsClaimed(uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ActivityCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ActivityResolved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BetPlaced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketListed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketSold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketUnlisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WinningsClaimed"): EventFragment;
}

export interface ActivityCreatedEventObject {
  activityId: BigNumber;
  description: string;
  choices: string[];
  endTime: BigNumber;
  initialPool: BigNumber;
}
export type ActivityCreatedEvent = TypedEvent<
  [BigNumber, string, string[], BigNumber, BigNumber],
  ActivityCreatedEventObject
>;

export type ActivityCreatedEventFilter = TypedEventFilter<ActivityCreatedEvent>;

export interface ActivityResolvedEventObject {
  activityId: BigNumber;
  winningChoice: BigNumber;
}
export type ActivityResolvedEvent = TypedEvent<
  [BigNumber, BigNumber],
  ActivityResolvedEventObject
>;

export type ActivityResolvedEventFilter =
  TypedEventFilter<ActivityResolvedEvent>;

export interface BetPlacedEventObject {
  activityId: BigNumber;
  player: string;
  choiceIndex: BigNumber;
  amount: BigNumber;
  tokenId: BigNumber;
}
export type BetPlacedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber],
  BetPlacedEventObject
>;

export type BetPlacedEventFilter = TypedEventFilter<BetPlacedEvent>;

export interface TicketListedEventObject {
  tokenId: BigNumber;
  seller: string;
  price: BigNumber;
}
export type TicketListedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  TicketListedEventObject
>;

export type TicketListedEventFilter = TypedEventFilter<TicketListedEvent>;

export interface TicketSoldEventObject {
  tokenId: BigNumber;
  seller: string;
  buyer: string;
  price: BigNumber;
}
export type TicketSoldEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  TicketSoldEventObject
>;

export type TicketSoldEventFilter = TypedEventFilter<TicketSoldEvent>;

export interface TicketUnlistedEventObject {
  tokenId: BigNumber;
}
export type TicketUnlistedEvent = TypedEvent<
  [BigNumber],
  TicketUnlistedEventObject
>;

export type TicketUnlistedEventFilter = TypedEventFilter<TicketUnlistedEvent>;

export interface WinningsClaimedEventObject {
  tokenId: BigNumber;
  player: string;
  amount: BigNumber;
}
export type WinningsClaimedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  WinningsClaimedEventObject
>;

export type WinningsClaimedEventFilter = TypedEventFilter<WinningsClaimedEvent>;

export interface EasyBet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EasyBetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _activityCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    betTicket(overrides?: CallOverrides): Promise<[string]>;

    betToken(overrides?: CallOverrides): Promise<[string]>;

    buyTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimWinnings(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createActivity(
      _description: PromiseOrValue<string>,
      _choices: PromiseOrValue<string>[],
      _endTime: PromiseOrValue<BigNumberish>,
      _initialPoolAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getActivity(
      _activityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string[],
        BigNumber,
        BigNumber,
        boolean,
        BigNumber
      ] & {
        id: BigNumber;
        description: string;
        choices: string[];
        endTime: BigNumber;
        totalPool: BigNumber;
        resolved: boolean;
        winningChoice: BigNumber;
      }
    >;

    getChoiceBetAmount(
      _activityId: PromiseOrValue<BigNumberish>,
      _choiceIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    listTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    notary(overrides?: CallOverrides): Promise<[string]>;

    placeBet(
      _activityId: PromiseOrValue<BigNumberish>,
      _choiceIndex: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    resolveActivity(
      _activityId: PromiseOrValue<BigNumberish>,
      _winningChoice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sellOrders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        tokenId: BigNumber;
        seller: string;
        price: BigNumber;
      }
    >;

    unlistTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  _activityCounter(overrides?: CallOverrides): Promise<BigNumber>;

  betTicket(overrides?: CallOverrides): Promise<string>;

  betToken(overrides?: CallOverrides): Promise<string>;

  buyTicket(
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimWinnings(
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createActivity(
    _description: PromiseOrValue<string>,
    _choices: PromiseOrValue<string>[],
    _endTime: PromiseOrValue<BigNumberish>,
    _initialPoolAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getActivity(
    _activityId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string[], BigNumber, BigNumber, boolean, BigNumber] & {
      id: BigNumber;
      description: string;
      choices: string[];
      endTime: BigNumber;
      totalPool: BigNumber;
      resolved: boolean;
      winningChoice: BigNumber;
    }
  >;

  getChoiceBetAmount(
    _activityId: PromiseOrValue<BigNumberish>,
    _choiceIndex: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  listTicket(
    _tokenId: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  notary(overrides?: CallOverrides): Promise<string>;

  placeBet(
    _activityId: PromiseOrValue<BigNumberish>,
    _choiceIndex: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  resolveActivity(
    _activityId: PromiseOrValue<BigNumberish>,
    _winningChoice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sellOrders(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber] & {
      tokenId: BigNumber;
      seller: string;
      price: BigNumber;
    }
  >;

  unlistTicket(
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _activityCounter(overrides?: CallOverrides): Promise<BigNumber>;

    betTicket(overrides?: CallOverrides): Promise<string>;

    betToken(overrides?: CallOverrides): Promise<string>;

    buyTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimWinnings(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createActivity(
      _description: PromiseOrValue<string>,
      _choices: PromiseOrValue<string>[],
      _endTime: PromiseOrValue<BigNumberish>,
      _initialPoolAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getActivity(
      _activityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string[],
        BigNumber,
        BigNumber,
        boolean,
        BigNumber
      ] & {
        id: BigNumber;
        description: string;
        choices: string[];
        endTime: BigNumber;
        totalPool: BigNumber;
        resolved: boolean;
        winningChoice: BigNumber;
      }
    >;

    getChoiceBetAmount(
      _activityId: PromiseOrValue<BigNumberish>,
      _choiceIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    notary(overrides?: CallOverrides): Promise<string>;

    placeBet(
      _activityId: PromiseOrValue<BigNumberish>,
      _choiceIndex: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    resolveActivity(
      _activityId: PromiseOrValue<BigNumberish>,
      _winningChoice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    sellOrders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        tokenId: BigNumber;
        seller: string;
        price: BigNumber;
      }
    >;

    unlistTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ActivityCreated(uint256,string,string[],uint256,uint256)"(
      activityId?: PromiseOrValue<BigNumberish> | null,
      description?: null,
      choices?: null,
      endTime?: null,
      initialPool?: null
    ): ActivityCreatedEventFilter;
    ActivityCreated(
      activityId?: PromiseOrValue<BigNumberish> | null,
      description?: null,
      choices?: null,
      endTime?: null,
      initialPool?: null
    ): ActivityCreatedEventFilter;

    "ActivityResolved(uint256,uint256)"(
      activityId?: PromiseOrValue<BigNumberish> | null,
      winningChoice?: null
    ): ActivityResolvedEventFilter;
    ActivityResolved(
      activityId?: PromiseOrValue<BigNumberish> | null,
      winningChoice?: null
    ): ActivityResolvedEventFilter;

    "BetPlaced(uint256,address,uint256,uint256,uint256)"(
      activityId?: PromiseOrValue<BigNumberish> | null,
      player?: PromiseOrValue<string> | null,
      choiceIndex?: null,
      amount?: null,
      tokenId?: null
    ): BetPlacedEventFilter;
    BetPlaced(
      activityId?: PromiseOrValue<BigNumberish> | null,
      player?: PromiseOrValue<string> | null,
      choiceIndex?: null,
      amount?: null,
      tokenId?: null
    ): BetPlacedEventFilter;

    "TicketListed(uint256,address,uint256)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      price?: null
    ): TicketListedEventFilter;
    TicketListed(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      price?: null
    ): TicketListedEventFilter;

    "TicketSold(uint256,address,address,uint256)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null,
      price?: null
    ): TicketSoldEventFilter;
    TicketSold(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null,
      price?: null
    ): TicketSoldEventFilter;

    "TicketUnlisted(uint256)"(
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TicketUnlistedEventFilter;
    TicketUnlisted(
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TicketUnlistedEventFilter;

    "WinningsClaimed(uint256,address,uint256)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      player?: PromiseOrValue<string> | null,
      amount?: null
    ): WinningsClaimedEventFilter;
    WinningsClaimed(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      player?: PromiseOrValue<string> | null,
      amount?: null
    ): WinningsClaimedEventFilter;
  };

  estimateGas: {
    _activityCounter(overrides?: CallOverrides): Promise<BigNumber>;

    betTicket(overrides?: CallOverrides): Promise<BigNumber>;

    betToken(overrides?: CallOverrides): Promise<BigNumber>;

    buyTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimWinnings(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createActivity(
      _description: PromiseOrValue<string>,
      _choices: PromiseOrValue<string>[],
      _endTime: PromiseOrValue<BigNumberish>,
      _initialPoolAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getActivity(
      _activityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChoiceBetAmount(
      _activityId: PromiseOrValue<BigNumberish>,
      _choiceIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    notary(overrides?: CallOverrides): Promise<BigNumber>;

    placeBet(
      _activityId: PromiseOrValue<BigNumberish>,
      _choiceIndex: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    resolveActivity(
      _activityId: PromiseOrValue<BigNumberish>,
      _winningChoice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sellOrders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unlistTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _activityCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    betTicket(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    betToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimWinnings(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createActivity(
      _description: PromiseOrValue<string>,
      _choices: PromiseOrValue<string>[],
      _endTime: PromiseOrValue<BigNumberish>,
      _initialPoolAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getActivity(
      _activityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChoiceBetAmount(
      _activityId: PromiseOrValue<BigNumberish>,
      _choiceIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    notary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    placeBet(
      _activityId: PromiseOrValue<BigNumberish>,
      _choiceIndex: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    resolveActivity(
      _activityId: PromiseOrValue<BigNumberish>,
      _winningChoice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sellOrders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unlistTicket(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
