/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BetTicket } from "./BetTicket";
export type { BetToken } from "./BetToken";
export type { EasyBet } from "./EasyBet";
